/**
 * Kanonické modely (generace + objem, ne jen objem), seedované ručně -
 * FINÁLNÍ seznam s ověřenými typovými čísly (Wikipedie, veteranportal,
 * jawa-50.cz, cezetmania). Vazby odvozené z toho, co se v názvech potkává,
 * vedly k chybám (sdílené díly != stejný model), proto parser (parseModels.ts)
 * na tyto modely jen mapuje. Zdroj pravdy pro migraci 013_seed_models.sql
 * (`npx tsx scripts/generate-models-seed.ts`).
 *
 * Mimo rozsah: Simson, předválečné ČZ, ČZ 500, motokrosové typy 968/980,
 * „350 OHC“ (moderní Jawa, flag modern_jawa). Typ může sdílet víc modelů
 * (551 = obě Jawetty, 552 = všechny tři Stadiony). U ČZ 125/150 A/B/T/C je typ
 * označený písmenem (typeNumbers např. ['B']).
 */
export type CanonicalModel = {
  /** Stabilní klíč, používá se i jako models.id. */
  slug: string;
  brand: string;
  name: string;
  /** Řada - hrubé seskupení; rozsahy typů se rozvíjejí jen uvnitř řady. */
  family: string;
  displacement: number | null;
  typeNumbers: string[];
  aliases: string[];
  needsVerification: boolean;
  note: string | null;
};

export const CANONICAL_MODELS: readonly CanonicalModel[] = [
  {
    slug: 'pionyr-550',
    brand: 'Jawa',
    name: 'Jawa 50 typ 550 „Pařez“',
    family: 'Jawa 50',
    displacement: 50,
    typeNumbers: ['550'],
    aliases: ['pařez', 'typ 550'],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'pionyr-555',
    brand: 'Jawa',
    name: 'Jawa 50 typ 555',
    family: 'Jawa 50',
    displacement: 50,
    typeNumbers: ['555'],
    aliases: ['typ 555'],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'pionyr-05',
    brand: 'Jawa',
    name: 'Jawa 50 Pionýr typ 05',
    family: 'Jawa 50',
    displacement: 50,
    typeNumbers: ['05'],
    aliases: ['pionýr'],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'pionyr-20',
    brand: 'Jawa',
    name: 'Jawa 50 Pionýr typ 20',
    family: 'Jawa 50',
    displacement: 50,
    typeNumbers: ['20'],
    aliases: ['pionýr'],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'pionyr-21',
    brand: 'Jawa',
    name: 'Jawa 50 Pionýr typ 21 (Sport)',
    family: 'Jawa 50',
    displacement: 50,
    typeNumbers: ['21'],
    aliases: ['pionýr'],
    needsVerification: false,
    note: '„Sport“ záměrně není alias - kolidoval by s Jawettou Sport a dalšími.',
  },
  {
    slug: 'mustang-23',
    brand: 'Jawa',
    name: 'Jawa 50 typ 23 Mustang',
    family: 'Jawa 50',
    displacement: 50,
    typeNumbers: ['23'],
    aliases: ['mustang'],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'jawetta',
    brand: 'Jawa',
    name: 'Jawa 50 typ 551 Jawetta',
    family: 'Jawetta',
    displacement: 50,
    typeNumbers: ['551'],
    aliases: ['jawetta', 'jaweta'],
    needsVerification: false,
    note: 'Typ 551 (551/00 Standard, 551/01 De Luxe). NENÍ typ 550/555 ani 552/553. Samotné „551“ vede na obě Jawetty.',
  },
  {
    slug: 'jawetta-sport',
    brand: 'Jawa',
    name: 'Jawa 50 typ 551 Jawetta Sport',
    family: 'Jawetta',
    displacement: 50,
    typeNumbers: ['551'],
    aliases: ['jawetta sport', 'jaweta sport'],
    needsVerification: false,
    note: 'Typ 551 (551/02, 551/03 Sport Speciál). NENÍ typ 550/555 ani 552/553. Samotné „551“ vede na obě Jawetty.',
  },
  {
    slug: 'stadion-s11',
    brand: 'Stadion',
    name: 'Stadion S11',
    family: 'Stadion',
    displacement: 50,
    typeNumbers: ['552'],
    aliases: ['stadion', 's11'],
    needsVerification: false,
    note: 'Motor Jawa typ 552 u všech tří Stadionů; samotné „552“ vede na všechny tři. Motor 552 je odvozený z 551, díly Jawetta↔Stadion se sdílejí často.',
  },
  {
    slug: 'stadion-s22',
    brand: 'Stadion',
    name: 'Stadion S22',
    family: 'Stadion',
    displacement: 50,
    typeNumbers: ['552'],
    aliases: ['stadion', 's22'],
    needsVerification: false,
    note: 'Motor Jawa typ 552 u všech tří Stadionů; samotné „552“ vede na všechny tři. Motor 552 je odvozený z 551, díly Jawetta↔Stadion se sdílejí často.',
  },
  {
    slug: 'stadion-s23',
    brand: 'Stadion',
    name: 'Stadion S23',
    family: 'Stadion',
    displacement: 50,
    typeNumbers: ['552'],
    aliases: ['stadion', 's23'],
    needsVerification: false,
    note: 'Motor Jawa typ 552 u všech tří Stadionů; samotné „552“ vede na všechny tři. Motor 552 je odvozený z 551, díly Jawetta↔Stadion se sdílejí často.',
  },
  {
    slug: 'jawa-90-trail',
    brand: 'Jawa',
    name: 'Jawa 90 Trail',
    family: 'Jawa 90',
    displacement: null,
    typeNumbers: ['30', '36'],
    aliases: ['jawa 90', 'trail'],
    needsVerification: false,
    note: 'Samotné „Jawa 90“ vede na Trail i Roadster (nickname). Holé „90“ bez „Jawa“ se ignoruje, proto objem null.',
  },
  {
    slug: 'jawa-90-roadster',
    brand: 'Jawa',
    name: 'Jawa 90 Roadster',
    family: 'Jawa 90',
    displacement: null,
    typeNumbers: ['31', '37'],
    aliases: ['jawa 90', 'roadster'],
    needsVerification: false,
    note: 'Samotné „Jawa 90“ vede na Trail i Roadster (nickname). Holé „90“ bez „Jawa“ se ignoruje, proto objem null.',
  },
  {
    slug: 'perak-250',
    brand: 'Jawa',
    name: 'Jawa 250 Pérák (typ 11)',
    family: 'Jawa 250/350/500',
    displacement: 250,
    typeNumbers: ['11'],
    aliases: ['pérák'],
    needsVerification: false,
    note: 'Pérák NEMÁ typy 353/354.',
  },
  {
    slug: 'perak-350',
    brand: 'Jawa',
    name: 'Jawa 350 Pérák (typ 12)',
    family: 'Jawa 250/350/500',
    displacement: 350,
    typeNumbers: ['12'],
    aliases: ['pérák'],
    needsVerification: false,
    note: 'Pérák NEMÁ typy 353/354.',
  },
  {
    slug: 'ohc-500',
    brand: 'Jawa',
    name: 'Jawa 500 OHC (typ 15)',
    family: 'Jawa 250/350/500',
    displacement: 500,
    typeNumbers: ['15'],
    aliases: ['ohc'],
    needsVerification: false,
    note: 'Typ 15 (15/00 „Šnek“, 15/01, 15/02). „350 OHC“ je moderní Jawa (od 2017), ta se nemapuje - patří pod flag modern_jawa.',
  },
  {
    slug: 'kyvacka-250',
    brand: 'Jawa',
    name: 'Jawa-ČZ 250 Kývačka (typ 353)',
    family: 'Jawa 250/350/500',
    displacement: 250,
    typeNumbers: ['353'],
    aliases: ['kývačka', 'kýv.', 'kejvačka'],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'kyvacka-350',
    brand: 'Jawa',
    name: 'Jawa-ČZ 350 Kývačka (typ 354)',
    family: 'Jawa 250/350/500',
    displacement: 350,
    typeNumbers: ['354'],
    aliases: ['kývačka', 'kýv.', 'kejvačka'],
    needsVerification: false,
    note: 'Typ 354/02–354/04. „354/06“ je první 350 Panelka a mapuje se na panelka-350-360 i kyvacka-350.',
  },
  {
    slug: 'panelka-250-559',
    brand: 'Jawa',
    name: 'Jawa 250 typ 559 Panelka',
    family: 'Jawa 250/350/500',
    displacement: 250,
    typeNumbers: ['559'],
    aliases: ['panelka'],
    needsVerification: false,
    note: '1962–1974.',
  },
  {
    slug: 'panelka-250-592',
    brand: 'Jawa',
    name: 'Jawa 250 typ 592 Panelka',
    family: 'Jawa 250/350/500',
    displacement: 250,
    typeNumbers: ['592'],
    aliases: ['panelka'],
    needsVerification: false,
    note: '1969–1974.',
  },
  {
    slug: 'panelka-350-360',
    brand: 'Jawa',
    name: 'Jawa 350 typ 360 Panelka',
    family: 'Jawa 250/350/500',
    displacement: 350,
    typeNumbers: ['360'],
    aliases: ['panelka'],
    needsVerification: false,
    note: 'Včetně Automatic. „354/06“ = první 350 Panelka, mapuje se i na kyvacka-350.',
  },
  {
    slug: 'sport-250-590',
    brand: 'Jawa',
    name: 'Jawa 250 typ 590 Sport („Sportka“)',
    family: 'Jawa 250/350/500',
    displacement: 250,
    typeNumbers: ['590'],
    aliases: ['sportka', 'californian'],
    needsVerification: false,
    note: 'Včetně 590 Californian.',
  },
  {
    slug: 'sport-350-361',
    brand: 'Jawa',
    name: 'Jawa 350 typ 361 Sport („Sportka“)',
    family: 'Jawa 250/350/500',
    displacement: 350,
    typeNumbers: ['361'],
    aliases: ['sportka', 'californian'],
    needsVerification: false,
    note: 'Včetně 361 Californian.',
  },
  {
    slug: 'californian-362',
    brand: 'Jawa',
    name: 'Jawa 350 typ 362 Californian',
    family: 'Jawa 250/350/500',
    displacement: 350,
    typeNumbers: ['362'],
    aliases: ['californian'],
    needsVerification: false,
    note: 'Alias „californian“ bez typu vede na 590, 361 i 362.',
  },
  {
    slug: 'jawa-350-634',
    brand: 'Jawa',
    name: 'Jawa 350 typ 634',
    family: 'Jawa 250/350/500',
    displacement: 350,
    typeNumbers: ['634'],
    aliases: [],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'jawa-350-638',
    brand: 'Jawa',
    name: 'Jawa 350 typ 638',
    family: 'Jawa 250/350/500',
    displacement: 350,
    typeNumbers: ['638'],
    aliases: [],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'jawa-350-639',
    brand: 'Jawa',
    name: 'Jawa 350 typ 639',
    family: 'Jawa 250/350/500',
    displacement: 350,
    typeNumbers: ['639'],
    aliases: [],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'jawa-350-640',
    brand: 'Jawa',
    name: 'Jawa 350 typ 640',
    family: 'Jawa 250/350/500',
    displacement: 350,
    typeNumbers: ['640'],
    aliases: [],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'velorex-350',
    brand: 'Velorex',
    name: 'Velorex 350',
    family: 'Velorex',
    displacement: 350,
    typeNumbers: [],
    aliases: ['velorex'],
    needsVerification: false,
    note: 'Tříkolka s motorem Jawa 350.',
  },
  {
    slug: 'jawa-cz-125-355',
    brand: 'Jawa',
    name: 'Jawa-ČZ 125 typ 355',
    family: 'Jawa-ČZ',
    displacement: 125,
    typeNumbers: ['355'],
    aliases: [],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'jawa-cz-175-356',
    brand: 'Jawa',
    name: 'Jawa-ČZ 175 typ 356',
    family: 'Jawa-ČZ',
    displacement: 175,
    typeNumbers: ['356'],
    aliases: ['kývačka 175', 'malá kývačka'],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'cz-150-352',
    brand: 'ČZ',
    name: 'ČZ 150 typ 352',
    family: 'ČZ',
    displacement: 150,
    typeNumbers: ['352'],
    aliases: [],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'cz-125-a',
    brand: 'ČZ',
    name: 'ČZ 125 A',
    family: 'ČZ',
    displacement: 125,
    typeNumbers: ['A'],
    aliases: [],
    needsVerification: false,
    note: 'Typ je označen písmenem.',
  },
  {
    slug: 'cz-125-b',
    brand: 'ČZ',
    name: 'ČZ 125 B',
    family: 'ČZ',
    displacement: 125,
    typeNumbers: ['B'],
    aliases: [],
    needsVerification: false,
    note: 'Typ je označen písmenem.',
  },
  {
    slug: 'cz-125-t',
    brand: 'ČZ',
    name: 'ČZ 125 T',
    family: 'ČZ',
    displacement: 125,
    typeNumbers: ['T'],
    aliases: [],
    needsVerification: false,
    note: 'Typ je označen písmenem.',
  },
  {
    slug: 'cz-125-c',
    brand: 'ČZ',
    name: 'ČZ 125 C',
    family: 'ČZ',
    displacement: 125,
    typeNumbers: ['C'],
    aliases: [],
    needsVerification: false,
    note: 'Typ je označen písmenem; „125/150 C“ vede na cz-125-c i cz-150-c.',
  },
  {
    slug: 'cz-150-c',
    brand: 'ČZ',
    name: 'ČZ 150 C',
    family: 'ČZ',
    displacement: 150,
    typeNumbers: ['C'],
    aliases: [],
    needsVerification: false,
    note: 'Typ je označen písmenem; „125/150 C“ vede na cz-125-c i cz-150-c.',
  },
  {
    slug: 'cz-150-miss',
    brand: 'ČZ',
    name: 'ČZ 150 Miss Kevelos',
    family: 'ČZ',
    displacement: 150,
    typeNumbers: [],
    aliases: ['miss'],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'cz-125-453',
    brand: 'ČZ',
    name: 'ČZ 125 typ 453',
    family: 'ČZ',
    displacement: 125,
    typeNumbers: ['453'],
    aliases: [],
    needsVerification: false,
    note: 'Standard, De Luxe.',
  },
  {
    slug: 'cz-125-473',
    brand: 'ČZ',
    name: 'ČZ 125 typ 473 Sport',
    family: 'ČZ',
    displacement: 125,
    typeNumbers: ['473'],
    aliases: [],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'cz-175-450',
    brand: 'ČZ',
    name: 'ČZ 175 typ 450',
    family: 'ČZ',
    displacement: 175,
    typeNumbers: ['450'],
    aliases: [],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'cz-175-470',
    brand: 'ČZ',
    name: 'ČZ 175 typ 470 Sport',
    family: 'ČZ',
    displacement: 175,
    typeNumbers: ['470'],
    aliases: [],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'cz-250-455',
    brand: 'ČZ',
    name: 'ČZ 250 typ 455',
    family: 'ČZ',
    displacement: 250,
    typeNumbers: ['455'],
    aliases: [],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'cz-250-475',
    brand: 'ČZ',
    name: 'ČZ 250 typ 475 Sport',
    family: 'ČZ',
    displacement: 250,
    typeNumbers: ['475'],
    aliases: [],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'cz-125-476',
    brand: 'ČZ',
    name: 'ČZ 125 typ 476',
    family: 'ČZ',
    displacement: 125,
    typeNumbers: ['476'],
    aliases: [],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'cz-175-477',
    brand: 'ČZ',
    name: 'ČZ 175 typ 477',
    family: 'ČZ',
    displacement: 175,
    typeNumbers: ['477'],
    aliases: [],
    needsVerification: false,
    note: '„Pařížanka“.',
  },
  {
    slug: 'cz-125-488',
    brand: 'ČZ',
    name: 'ČZ 125 typ 488',
    family: 'ČZ',
    displacement: 125,
    typeNumbers: ['488'],
    aliases: [],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'cz-175-487',
    brand: 'ČZ',
    name: 'ČZ 175/180 typ 487',
    family: 'ČZ',
    displacement: 175,
    typeNumbers: ['487'],
    aliases: [],
    needsVerification: false,
    note: '180 je pozdější provedení typu 487.',
  },
  {
    slug: 'cz-250-471',
    brand: 'ČZ',
    name: 'ČZ 250 typ 471',
    family: 'ČZ',
    displacement: 250,
    typeNumbers: ['471'],
    aliases: [],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'cz-350-472',
    brand: 'ČZ',
    name: 'ČZ 350 typ 472',
    family: 'ČZ',
    displacement: 350,
    typeNumbers: ['472'],
    aliases: [],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'cezeta-501',
    brand: 'ČZ',
    name: 'ČZ 175/501 Čezeta (skútr)',
    family: 'Čezeta',
    displacement: 175,
    typeNumbers: ['501'],
    aliases: ['čezeta', 'cezeta', 'čezetu', 'čezety', 'čezet'],
    needsVerification: false,
    note: 'Shopy říkají „Čezeta“ i běžným ČZ („Čezetu 125“): „Čezeta“ + objem bez typu 501/502 se NEmapuje na skútr, jen brand ČZ. Samotné „Čezeta“ vede na oba.',
  },
  {
    slug: 'cezeta-502',
    brand: 'ČZ',
    name: 'ČZ 175/502 Čezeta (skútr)',
    family: 'Čezeta',
    displacement: 175,
    typeNumbers: ['502'],
    aliases: ['čezeta', 'cezeta', 'čezetu', 'čezety', 'čezet'],
    needsVerification: false,
    note: 'Shopy říkají „Čezeta“ i běžným ČZ („Čezetu 125“): „Čezeta“ + objem bez typu 501/502 se NEmapuje na skútr, jen brand ČZ. Samotné „Čezeta“ vede na oba.',
  },
  {
    slug: 'babetta-207',
    brand: 'Babetta',
    name: 'Babetta 207',
    family: 'Babetta',
    displacement: null,
    typeNumbers: ['207'],
    aliases: [],
    needsVerification: false,
    note: 'Objem doplnit.',
  },
  {
    slug: 'babetta-210',
    brand: 'Babetta',
    name: 'Babetta 210',
    family: 'Babetta',
    displacement: null,
    typeNumbers: ['210'],
    aliases: [],
    needsVerification: false,
    note: 'Objem doplnit.',
  },
  {
    slug: 'babetta-225',
    brand: 'Babetta',
    name: 'Babetta 225',
    family: 'Babetta',
    displacement: null,
    typeNumbers: ['225'],
    aliases: [],
    needsVerification: false,
    note: 'Objem doplnit.',
  },
  {
    slug: 'babetta-228',
    brand: 'Babetta',
    name: 'Babetta 228',
    family: 'Babetta',
    displacement: null,
    typeNumbers: ['228'],
    aliases: [],
    needsVerification: false,
    note: 'Objem doplnit.',
  },
  {
    slug: 'babetta-134',
    brand: 'Babetta',
    name: 'Babetta 134 Stella',
    family: 'Babetta',
    displacement: null,
    typeNumbers: ['134'],
    aliases: ['stella', 'star', 'star 134'],
    needsVerification: false,
    note: 'Objem doplnit.',
  },
];
