/**
 * Kanonické modely (generace + objem, ne jen objem), seedované ručně.
 * Vazby odvozené z toho, co se v názvech potkává, vedly k chybám (sdílené
 * díly != stejný model), proto parser (parseModels.ts) na tyto modely jen
 * mapuje. Zdroj pravdy pro migraci 013_seed_models.sql
 * (`npx tsx scripts/generate-models-seed.ts`).
 *
 * Pravidla seedu:
 * - typová čísla označená "ověřit" se NEVYPLŇUJÍ do typeNumbers, jen do note,
 * - ČZ modely se neseedují (typy 355, 450, 453, 455, 470, 471, 472, 476, 477,
 *   487, 488 doplní Adam ručně podle katalogu),
 * - Simson je mimo rozsah.
 */
export type CanonicalModel = {
  /** Stabilní klíč, používá se i jako models.id. */
  slug: string;
  brand: string;
  name: string;
  /** Řada - hrubé seskupení; rozsahy typů se rozvíjejí jen uvnitř řady. */
  family: string;
  displacement: number | null;
  typeNumbers: string[];
  aliases: string[];
  needsVerification: boolean;
  note: string | null;
};

const JAWA_50 = 'Jawa 50';
const JAWA_175_500 = 'Jawa 175–500';

export const CANONICAL_MODELS: readonly CanonicalModel[] = [
  // --- Jawa 50 ---
  {
    slug: 'pionyr-550',
    brand: 'Jawa',
    name: 'Jawa 50 typ 550 „Pařez“',
    family: JAWA_50,
    displacement: 50,
    typeNumbers: ['550'],
    aliases: ['pařez', 'typ 550'],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'pionyr-555',
    brand: 'Jawa',
    name: 'Jawa 50 typ 555',
    family: JAWA_50,
    displacement: 50,
    typeNumbers: ['555'],
    aliases: ['typ 555'],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'pionyr-05',
    brand: 'Jawa',
    name: 'Jawa 50 Pionýr typ 05',
    family: JAWA_50,
    displacement: 50,
    typeNumbers: ['05'],
    aliases: ['pionýr'],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'pionyr-20',
    brand: 'Jawa',
    name: 'Jawa 50 Pionýr typ 20',
    family: JAWA_50,
    displacement: 50,
    typeNumbers: ['20'],
    aliases: ['pionýr'],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'pionyr-21',
    brand: 'Jawa',
    name: 'Jawa 50 Pionýr typ 21 (Sport)',
    family: JAWA_50,
    displacement: 50,
    typeNumbers: ['21'],
    aliases: ['pionýr'],
    needsVerification: false,
    note: '„Sport“ záměrně není alias - kolidoval by s Jawettou Sport a dalšími.',
  },
  {
    slug: 'mustang-23',
    brand: 'Jawa',
    name: 'Jawa 50 typ 23 Mustang',
    family: JAWA_50,
    displacement: 50,
    typeNumbers: ['23'],
    aliases: ['mustang'],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'jawetta',
    brand: 'Jawa',
    name: 'Jawetta',
    family: 'Jawetta',
    displacement: null,
    typeNumbers: [],
    aliases: ['jawetta'],
    needsVerification: true,
    note: 'Samostatný model, NENÍ typ 550/555 (sdílí s 555 motor). Typy 552/553 ověřit. Objem doplnit.',
  },
  {
    slug: 'jawetta-sport',
    brand: 'Jawa',
    name: 'Jawetta Sport',
    family: 'Jawetta',
    displacement: null,
    typeNumbers: [],
    aliases: ['jawetta sport'],
    needsVerification: true,
    note: 'Samostatný model, NENÍ typ 550/555 (sdílí s 555 motor). Typy 552/553 ověřit. Objem doplnit.',
  },
  {
    slug: 'stadion-s11',
    brand: 'Stadion',
    name: 'Stadion S11',
    family: 'Stadion',
    displacement: null,
    typeNumbers: [],
    aliases: ['stadion', 's11'],
    needsVerification: true,
    note: 'Vztah k motorům Jawa 50 ověřit. Objem doplnit.',
  },
  {
    slug: 'stadion-s22',
    brand: 'Stadion',
    name: 'Stadion S22',
    family: 'Stadion',
    displacement: null,
    typeNumbers: [],
    aliases: ['stadion', 's22'],
    needsVerification: true,
    note: 'Vztah k motorům Jawa 50 ověřit. Objem doplnit.',
  },
  {
    slug: 'stadion-s23',
    brand: 'Stadion',
    name: 'Stadion S23',
    family: 'Stadion',
    displacement: null,
    typeNumbers: [],
    aliases: ['stadion', 's23'],
    needsVerification: true,
    note: 'Vztah k motorům Jawa 50 ověřit. Objem doplnit.',
  },
  {
    slug: 'jawa-90',
    brand: 'Jawa',
    name: 'Jawa 90 (Cross aj.)',
    family: 'Jawa 90',
    displacement: 90,
    typeNumbers: [],
    aliases: ['jawa 90'],
    needsVerification: true,
    note: 'Alias „jawa 90“ je jednogenerační zkratka, aby šel model zachytit (displacement level by na něj jinak nevedl). „Californian“ NENÍ alias - ověřit, k čemu patří.',
  },

  // --- Jawa 175–500 ---
  {
    slug: 'perak-250',
    brand: 'Jawa',
    name: 'Jawa 250 Pérák (typ 11)',
    family: JAWA_175_500,
    displacement: 250,
    typeNumbers: ['11'],
    aliases: ['pérák'],
    needsVerification: false,
    note: 'Pérák NEMÁ typy 353/354.',
  },
  {
    slug: 'perak-350',
    brand: 'Jawa',
    name: 'Jawa 350 Pérák (typ 12)',
    family: JAWA_175_500,
    displacement: 350,
    typeNumbers: ['12'],
    aliases: ['pérák'],
    needsVerification: false,
    note: 'Pérák NEMÁ typy 353/354.',
  },
  {
    slug: 'ohc-350',
    brand: 'Jawa',
    name: 'Jawa 350 OHC',
    family: JAWA_175_500,
    displacement: 350,
    typeNumbers: [],
    aliases: ['ohc'],
    needsVerification: true,
    note: 'Typové číslo ověřit.',
  },
  {
    slug: 'ohc-500',
    brand: 'Jawa',
    name: 'Jawa 500 OHC',
    family: JAWA_175_500,
    displacement: 500,
    typeNumbers: [],
    aliases: ['ohc'],
    needsVerification: true,
    note: 'Typové číslo ověřit.',
  },
  {
    slug: 'kyvacka-250',
    brand: 'Jawa',
    name: 'Jawa 250 Kývačka (typ 353)',
    family: JAWA_175_500,
    displacement: 250,
    typeNumbers: ['353'],
    aliases: ['kývačka', 'kýv.', 'kejvačka'],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'kyvacka-350',
    brand: 'Jawa',
    name: 'Jawa 350 Kývačka (typ 354)',
    family: JAWA_175_500,
    displacement: 350,
    typeNumbers: ['354'],
    aliases: ['kývačka', 'kýv.', 'kejvačka'],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'kyvacka-175',
    brand: 'Jawa',
    name: 'Jawa 175 Kývačka (typ 356)',
    family: JAWA_175_500,
    displacement: 175,
    typeNumbers: ['356'],
    aliases: ['kývačka', 'kýv.', 'kejvačka'],
    needsVerification: false,
    note: 'Aliasy převzaty z Kývaček 250/350 (v zadání uvedeny jen u nich).',
  },
  {
    slug: 'jawa-250-559',
    brand: 'Jawa',
    name: 'Jawa 250 typ 559',
    family: JAWA_175_500,
    displacement: 250,
    typeNumbers: ['559'],
    aliases: [],
    needsVerification: true,
    note: 'Přechod Kývačka/Panelka, zařazení ověřit.',
  },
  {
    slug: 'panelka-250',
    brand: 'Jawa',
    name: 'Jawa 250 Panelka',
    family: JAWA_175_500,
    displacement: 250,
    typeNumbers: [],
    aliases: ['panelka'],
    needsVerification: true,
    note: 'Typová čísla ověřit (NE 634, NE 638–640).',
  },
  {
    slug: 'panelka-350',
    brand: 'Jawa',
    name: 'Jawa 350 Panelka',
    family: JAWA_175_500,
    displacement: 350,
    typeNumbers: [],
    aliases: ['panelka'],
    needsVerification: true,
    note: 'Typová čísla ověřit (NE 634, NE 638–640).',
  },
  {
    slug: 'jawa-350-634',
    brand: 'Jawa',
    name: 'Jawa 350 typ 634',
    family: JAWA_175_500,
    displacement: 350,
    typeNumbers: ['634'],
    aliases: [],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'jawa-350-638',
    brand: 'Jawa',
    name: 'Jawa 350 typ 638',
    family: JAWA_175_500,
    displacement: 350,
    typeNumbers: ['638'],
    aliases: [],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'jawa-350-639',
    brand: 'Jawa',
    name: 'Jawa 350 typ 639',
    family: JAWA_175_500,
    displacement: 350,
    typeNumbers: ['639'],
    aliases: [],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'jawa-350-640',
    brand: 'Jawa',
    name: 'Jawa 350 typ 640',
    family: JAWA_175_500,
    displacement: 350,
    typeNumbers: ['640'],
    aliases: [],
    needsVerification: false,
    note: null,
  },
  {
    slug: 'velorex-350',
    brand: 'Velorex',
    name: 'Velorex 350',
    family: 'Velorex',
    displacement: 350,
    typeNumbers: [],
    aliases: ['velorex'],
    needsVerification: false,
    note: 'Brand „Velorex“ (v zadání zařazeno pod Jawa 175–500).',
  },

  // --- Babetta ---
  ...['207', '210', '225', '228'].map((type): CanonicalModel => ({
    slug: `babetta-${type}`,
    brand: 'Babetta',
    name: `Babetta ${type}`,
    family: 'Babetta',
    displacement: null,
    typeNumbers: [type],
    aliases: [],
    needsVerification: false,
    note: 'Objem doplnit.',
  })),
  {
    slug: 'babetta-134',
    brand: 'Babetta',
    name: 'Babetta 134',
    family: 'Babetta',
    displacement: null,
    typeNumbers: ['134'],
    aliases: [],
    needsVerification: true,
    note: 'Aliasy star/stella ověřit (zatím nejsou mezi aliasy). Objem doplnit.',
  },

  // --- Čezeta ---
  {
    slug: 'cezeta',
    brand: 'Čezeta',
    name: 'Čezeta',
    family: 'Čezeta',
    displacement: null,
    typeNumbers: [],
    aliases: ['čezeta'],
    needsVerification: true,
    note: 'Typy ověřit.',
  },
];
